// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/yumosx/poc/internal/handler"
	"github.com/yumosx/poc/internal/repo"
	"github.com/yumosx/poc/internal/repo/dao"
	"github.com/yumosx/poc/internal/service"
)

// Injectors from wire.go:

func InitApp() *handler.Handler {
	db := initDB()
	aiDao := dao.NewAIDao(db)
	taskDao := dao.NewTaskDao(db)
	aiRepo := repo.NewAIRepo(aiDao, taskDao)
	llmHandler := initLLMHandler()
	aiService := service.NewAIService(aiRepo, llmHandler)
	handlerHandler := handler.NewHandler(aiService)
	return handlerHandler
}
